### ISSUE TITLE
--release flag fails

### ISSUE THREAD

**Issue by jgardona** [RazrFalcon/cargo-bloat#102]
**win10 x64
msys2 ucrt64**

When passing --release, cargo-bloat fails to find the executable:

```
$ cargo bloat --release -n 10
   Compiling example v0.1.0 (C:\Users\jgardona\Workspace\rust\example)
    Finished release [optimized] target(s) in 6.74s
Error: failed to open a file 'C:\Users\jgardona\Workspace\rust\example\target\release\example.pdb'.
```

**Comment by RazrFalcon** [comment]
Does this file actually exist? If so, try running it though https://github.com/willglynn/pdb/blob/master/examples/pdb_symbols.rs example. If it fails as well - then it's a `pdb` crate bug. Or we have to update ours.

**Comment by jgardona** [comment]
My folder doesn't have the pdb file, but I think its working as expected.
Doesn't --release flag removes it?
When running for debug it works as expected.

![image](https://github.com/RazrFalcon/cargo-bloat/assets/146892539/dcb29793-560a-443d-9094-43fddfb1550e)

**Comment by jgardona** [comment]
Also, my projects are using the following configuration for [profile.release]
```toml
[profile.release]
strip = true
lto = "thin"
opt-level = "z"
panic = "abort"
```

**Comment by RazrFalcon** [comment]
Try removing `strip = true`
