### ISSUE TITLE
Standalone exe to analyze any executable

### ISSUE THREAD

**Issue by stepancheg** [RazrFalcon/cargo-bloat#18]
Currently `cargo bloat` supports only certain executables built by `cargo`.

Would be convenient to have an utility not tied to cargo to analyze any rust binary.

**Comment by RazrFalcon** [comment]
Yes. This is planed. But it will require additional checks, because now it assumes than exe has a "debug" info.

**Comment by RazrFalcon** [comment]
Closing this one, because `cargo-bloat` uses `cargo build` metadata for analyzing.

**Comment by ia0** [comment]
This was not completed right? This was closed as not planned.

**Comment by RazrFalcon** [comment]
Yes. Not planned.
