### ISSUE TITLE
Support running cargo bloat on only one crate in a workspace

### ISSUE THREAD

**Issue by jonhoo** [RazrFalcon/cargo-bloat#21]
I have a large project with a `[workspace]` at [the root](https://github.com/mit-pdos/distributary/blob/master/Cargo.toml), and several subcrates. I'd like to run cargo bloat on only one of those subcrates, but even if I run cargo bloat in the subdirectory of one of the crates, it looks as though it still parses the entire workspace (that is, all the crates). For example, if I run `cargo bloat` in [`basics/`](https://github.com/mit-pdos/distributary/tree/master/basics), I still get an error because of an unsupported Cargo feature (#20) in [`benchmarks/Cargo.toml`](https://github.com/mit-pdos/distributary/blob/master/benchmarks/Cargo.toml#L1). The `--filter` flag does not seem to help here either (I'm guessing it just does grepping after the fact).

The ability to only scan one crate is not only useful, but also nearly essential for very large projects. Running analysis over the whole workspace would be pretty expensive, especially if you only "care" about one subcrate.

**Comment by RazrFalcon** [comment]
cargo bloat, as expected, uses cargo. So it works exactly as cargo and can't behave differently.

Maybe you wan't to use --bin and --example flags?

**Comment by jonhoo** [comment]
It doesn't seem like that's the case here? With `cargo` I can run `cargo` in a particular subcrate and have it operate only on that crate (including only its dependencies and relevant `Cargo.toml` file). There's also `cargo -p` that lets you do the same. But `cargo-bloat` seems to always operate on the entire workspace?

**Comment by RazrFalcon** [comment]
Can you make an example or give a link to the repo? At the moment, cargo-bloat behaves exactly as cargo itself. There are no specific code for this.

**Comment by jonhoo** [comment]
The repository I linked to in the post above is an example. If you clone it and run, say, `cargo check` inside of the `basics/` directory, it will only compile things relevant to that crate. If you run `cargo bloat`, it will complain about the unsupported feature in `benchmarks/Cargo.toml`, even though that's not related to `basics` at all.
