### ISSUE TITLE
In some cases, cargo reports it can't execute itself because it's not in the PATH

### ISSUE THREAD

**Issue by andy5995** [RazrFalcon/cargo-bloat#29]
**Problem**
If `cargo bloat` is run outside of a project directory, cargo reports that it can't execute itself because it's not in the PATH.

**Steps**

```
:~$ cargo bloat
Compiling ...
Error: failed to execute 'cargo'. It should be in the PATH.
```

**Possible Solution(s)**
Probably the same output should be shown as if `cargo run` were executed outside a project directory:

```
~$ cargo run
error: could not find `Cargo.toml` in `/home/andy` or any parent directory
```

**Notes**
This is a minor bug I found when someone suggested I run `cargo bloat` before I had reached section 1.3 of the book. I didn't understand that `cargo` really only has an effect when working with projects created with `cargo new`.

Output of `cargo version`: cargo 1.30.0 (36d96825d 2018-10-24)

OS platform: Debian Linux 9

**Comment by theronic** [comment]
This just bit me as well

**Comment by theronic** [comment]
How do I make this work for old projects?
