### ISSUE TITLE
Please remove only the relevant target directory before using `--time`

### ISSUE THREAD

**Issue by heidezomp** [RazrFalcon/cargo-bloat#33]
The new `--time` feature is cool! But it would be helpful if instead of running a full `cargo clean` beforehand, it would only remove the relevant directory (e.g. `target/debug`). Now my release build and documentation are also gone, and those take a pretty long time to build from scratch on my old and slow laptop.

**Comment by RazrFalcon** [comment]
Looks like I can remove `release` and/or `doc`, but not just `debug`. At least I can't find such an option. So I can add support for removing only the `release` dir while running `cargo-bloat --release` and in debug it will remove everything as previously.

And I don't think that removing the `target` dir without `cargo` is a good idea.

**Comment by jonhoo** [comment]
I think you definitely want to go through `cargo clean`, otherwise you'll run into weird cases with things like `CARGO_TARGET_DIR`.

**Comment by heidezomp** [comment]
I see what you mean with the `cargo clean` options. I agree with both of you on going through `cargo clean`. I think having the desired behavior only in release mode is better than nothing, so if you can add support for that, that would be great! :smile:

In the mean time I will see whether there is an issue on adding the desired behavior to `cargo clean`; if not, I'll add one. The currently provided options seem inconsistent to me anyway.

**Comment by heidezomp** [comment]
There didn't seem to be an issue about this yet, so I opened rust-lang/cargo#7021 :smile:
