### ISSUE TITLE
Cannot build 0.8.0 on Windows

### ISSUE THREAD

**Issue by cfredric** [RazrFalcon/cargo-bloat#38]
`cargo install cargo-bloat` fails on Windows with the following error message:

error[E0425]: cannot find function `collect_self_data` in this scope
   --> src\main.rs:594:23
    |
594 |                 data: collect_self_data(&artifact.path)?,
    |                       ^^^^^^^^^^^^^^^^^ not found in this scope

error: aborting due to previous error

For more information about this error, try `rustc --explain E0425`.
error: Could not compile `cargo-bloat`.

The same error occurs if I clone the repo and attempt to `cargo build` there.

It looks like this is because `collect_self_data` is cfg'ed to only be defined when compiling on non-OSX Unix targets.

**Comment by RazrFalcon** [comment]
Windows isn't supported.
