### ISSUE TITLE
executing binary results in obscure error

### ISSUE THREAD

**Issue by matthiaskrgr** [RazrFalcon/cargo-bloat#39]
running `./target/debug/cargo-bloat` terminates with `Error: qwe.`
`./target/debug/cargo-bloat bloat` works however. (can we suggest that instead printing "qwe" maybe?)

repo @ 74f19773beb90a5f5c1f5ea374536a46636963cb

**Comment by RazrFalcon** [comment]
I've forgot to remove a temporary message.

Anyway, you should run it only via `cargo bloat`. You can't run it directly.

**Comment by matthiaskrgr** [comment]
Is this a design choice?

In `cargo-cache`, I was able to solve this (I use clap) by using dummy subcommand and adding all the runtime

**Comment by RazrFalcon** [comment]
Yes. This is intentional. It can't be used directly.

Why do you wan't to do this?

**Comment by matthiaskrgr** [comment]
I just find it weird that running the binary directly does not work .. :/

**Comment by RazrFalcon** [comment]
Well, this is how all cargo tools works. This way you can write `cargo +nightly bloat` and it will work automatically.
