### ISSUE TITLE
Consider adding `--all` or removing `-n 20` default

### ISSUE THREAD

**Issue by kbknapp** [RazrFalcon/cargo-bloat#4]
From [my comment on reddit](https://www.reddit.com/r/rust/comments/7ospf1/cargobloat_find_out_what_takes_most_of_the_space/dscirar/). Even though it was quickly solved, I can't imagine I'll be the only one tripped up by this.

I ran `$ cargo bloat --release --crates` expecting to see all the crates but only got the top 20. It took me a while until I realized I needed to pass something like `$ cargo bloat --release -n 999 --crates` to see eerything.

Adding `--all` for "all lines" or simply removing the default of 20 would be good IMO. Personally I prefer just removing the default of 20 since people can cut down the number of lines with `-n` or tools like `head` just fine. If you'd prefer to add `--all`, I think it'd be good practice to output a line saying, `"Only outputting top 20 lines, use --all to see everything"` when no `-n` is used.

**Comment by RazrFalcon** [comment]
You can use `-n 0`. Will add it to help.
