### ISSUE TITLE
cargo bloat --release --crates not work

### ISSUE THREAD

**Issue by SharpKnifer** [RazrFalcon/cargo-bloat#44]
## Environment

* ** cargo-bloat version:**
cargo-bloat 0.6.3
* **Rust toolchain version:**
rustc 1.33.0-nightly (c76f3c374 2019-01-18)
* **Operating system:**
macOS
Darwin Kernel Version 18.0.0: Wed Aug 22 20:13:40 PDT 2018; root:xnu-4903.201.2~1/RELEASE_X86_64

## Problem description
I follow the readme file to use the cargo bloat.However the result does not seems like the sample result in readme file .
This is my cmd and result:
$ cargo bloat --release --crates
Compiling ...
Analyzing target/release/libtest.dylib

File  .text Size Name
0.0% 100.0%   0B .text section size, the file size is 26.4MiB

Note: numbers above are a result of guesswork. They are not 100% correct and never will be.

## Steps to reproduce

**Comment by RazrFalcon** [comment]
The latest version is 0.8.1
