### ISSUE TITLE
Missing `--package` flag

### ISSUE THREAD

**Issue by cwfitzgerald** [RazrFalcon/cargo-bloat#45]
## Information

Cargo Bloat Version:
`0.8.1`

Rustc Version:
`rustc 1.38.0-nightly (83e4eed16 2019-07-14)`

## Prior Art

Possibly tangentially related to #21, though I'm not sure.

## Issue

When I am running cargo bloat on my [project](https://github.com/cwfitzgerald/sarcasm-rs/tree/cc71e20d665dafa15b33b270e6c5a832f3abad47), it tells me that it only supports `bin` or `cdylib` targets. This is fine. However, the proper way to build my binary is `cargo build --package sarcasm --bin sarcasm`. There doesn't appear to be a proper way to pass through that information to cargo bloat so it invokes the proper build command.

I don't know how cargo bloat detects if there is a generated binary/where it is, but it may be possible to just add support for passing that flag through directly.

## Conclusion

If you need any more information, feel free to ask :smile:

Thanks for making this tool.

**Comment by RazrFalcon** [comment]
I hope that this is enough.

**Comment by cwfitzgerald** [comment]
That was the quickest issue fix known to man. Just pulled from git and that works perfectly! Thank you!
