### ISSUE TITLE
-n does not work on --crates

### ISSUE THREAD

**Issue by JayXon** [RazrFalcon/cargo-bloat#46]
It always print all the crates.

**Comment by RazrFalcon** [comment]
This is an expected behavior.

**Comment by JayXon** [comment]
Okay, but the help text says "Number of lines to show" so I assumed it should work.
Is there any reason to not support `-n` for `--crates`?

**Comment by RazrFalcon** [comment]
It was actually fixed in master already:

https://github.com/RazrFalcon/cargo-bloat/blob/dc39c4bfc2e5fc8c5e8dbf8b33ccd27c593dd4dd/src/main.rs#L243

The number of crates is usually pretty small and there are no reason to trim it.

**Comment by JayXon** [comment]
But the binary I'm analyzing has like 50 crates...

**Comment by RazrFalcon** [comment]
Is it a lot? A medium-sized binary will have tens of thousands of functions.

**Comment by JayXon** [comment]
It's not as many as functions of course, but it's still nice to be able to limit the output, like `bloaty` where `-n` works on all the sources.

**Comment by RazrFalcon** [comment]
Ok, I will revert it.

**Comment by JayXon** [comment]
Thanks!
