### ISSUE TITLE
JSON output format

### ISSUE THREAD

**Issue by theduke** [RazrFalcon/cargo-bloat#48]
I'd love to leverage the output of cargo-bloat in a development dashboard.

For this a `json` output format would be greatly appreciated.

**Comment by RazrFalcon** [comment]
Sure, I'll add it later.

**Comment by RazrFalcon** [comment]
By the way, what kind of output do you prefer? As is:

```json
[
  {
    "File": "0.4%",
    ".text": "5.6%",
    "Size": "8.8KiB",
    "Crate": "[Unknown]",
    "Name": "read_line_info"
  },
  {
    "File": "0.3%",
    ".text": "4.4%",
    "Size": "6.8KiB",
    "Crate": "std",
    "Name": "__rdos_backtrace_dwarf_add"
  }
]
```

or more low-level:

```json
{
  "file-size": 2527192,
  "text-section-size": 160154,
  "functions": [
    {
      "name": "read_line_info",
      "size": 9012
    },
    {
      "crate": "std",
      "name": "__rdos_backtrace_dwarf_add",
      "size": 6964
    }
  ]
}
```

**Comment by theduke** [comment]
I think the second variant would be more useful.

**Comment by theduke** [comment]
Thanks!

**Comment by RazrFalcon** [comment]
Feel free to report any issues.

**Comment by theduke** [comment]
Will do.

I'm working on a "cargo dashbaord" UI that ties together all the analysis tools in a nice interface, so I'll complain if I find any issues. ;)
