### ISSUE TITLE
Run on Library Crates

### ISSUE THREAD

**Issue by sunjay** [RazrFalcon/cargo-bloat#5]
Thanks for creating this tool! :smile: 

Is there a way to run cargo bloat on crates that are just libraries? If you need an executable to run on, I could pass `--example foo` to generate an executable for that particular example. I would like to use this on my crates to see if any functions/dependencies are taking up most of the binary generated by anyone using the crate.

**Comment by RazrFalcon** [comment]
>Is there a way to run cargo bloat on crates that are just libraries?
No, because executables and libraries are very different. Especially static libraries, which is the default.

Examples support is a good idea, but note that `cargo-bloat` will show only stuff that is used by example, so you have to use as many features of your library as possible.

**Comment by sunjay** [comment]
> Examples support is a good idea, but note that cargo-bloat will show only stuff that is used by example, so you have to use as many features of your library as possible.

That would be fine. I think having that much support would still be extremely helpful. :)

**Comment by CryZe** [comment]
I'm compiling my code to a static & dynamic library, so extending it to work on those cases would be really cool too.

**Comment by RazrFalcon** [comment]
@CryZe it's not possible due to the way executable and libraries are work. You can measure only executables.

**Comment by CryZe** [comment]
Can you elaborate why?

**Comment by RazrFalcon** [comment]
I'm not that good in this, but the basics look like this:
- The static library is just a pile of code (in c/c++/rust it's an actual archive file with objects and some metadata). No optimizations are made afaik.
- The dynamic library is something in between. It support optimization, but not LTO afaik.
- The executable file format usually has the `.text` section in which the compiled code contains. And all this tool doing is measuring so-called *symbols* size. You can call them functions or methods. But Rust (and C++) has two other problems:
  - Generics (hello Go). The library can define generics, but not use them by itself, so they will be instanced only in the executable, so you can't measure them in the library.
  - Inlining. Rust supports inlining which eliminates some functions completely. But there is no inlining in the static libraries (afaik) and only to some extend in dynamic library, so the results will be different.

**Comment by RazrFalcon** [comment]
Done.

**Comment by sunjay** [comment]
Thank you! :)

**Comment by kupiakos** [comment]
Any chance we can reconsider this for `staticlib`? [Bloaty supports them](https://github.com/google/bloaty/blob/master/doc/using.md#data-sources), so it's definitely possible in theory.

**Comment by RazrFalcon** [comment]
There is nothing interesting in `staticlib` and it doesn't affect the final binary in any way.
Remember, that `staticlib` is just an archive of an intermediate compiler output. It still has to be compiled.

**Comment by kupiakos** [comment]
There is interesting info in a `staticlib`, especially for embedded use cases that don't load in a traditional manner. A `staticlib` is a collection of `.o` files - it _is_ compiled, just not linked yet. It's not an `rlib`. While the output is imperfect (no LTO, for example), it's still useful data.
Bloaty supports analyzing a `.a`/static lib because it can still provide useful information.

**Comment by RazrFalcon** [comment]
I will rephrase: it's not interested for cargo-bloat use case.  cargo-bloat analyzes final binaries. That's it.

**Comment by kupiakos** [comment]
Why? I was planning on implementing this support, and would really rather not maintain project fork for a feature that I believe should be there in the first place. Right now we have to settle with Bloaty, which doesn't yet have Rust name demangling.

**Comment by RazrFalcon** [comment]
Because cargo-bloat prints `.text` section output. Can we get anything like this from static lib? I don't think so.
Can you show bloaty output?
