### ISSUE TITLE
cargo-bloat fails to find std libraries, it expects them to live in /usr/lib/rustlib

### ISSUE THREAD

**Issue by stefson** [RazrFalcon/cargo-bloat#51]
how to reproduce, with the example of a fresh git checkout: 
```
cd tmp && git clone https://github.com/eqrion/cbindgen.git
cd cbindgen
cargo bloat 
compiling...
Error: failed to find a dir with std libraries. Expected location: /usr/lib/rustlib/x86_64-unknown-linux-gnu/lib.
```

this is on a x86_64 machine, hence there's /usr/lib64/${RUSTVERSION}/ where rustlib resides. Not sure wether that is excentric behavior from my distro? :-)

**Comment by RazrFalcon** [comment]
What `rustc --print=sysroot` outputs?

**Comment by stefson** [comment]
here's the output:
```
rustc --print=sysroot
/usr
```

**Comment by RazrFalcon** [comment]
Do you have `rustlib` at all?

**Comment by stefson** [comment]
Sure, I've got full rust toolchain available. It's actually the case that `cargo build` is executed before `cargo bloat`, and the error only appears when `cargo build` has finished it's compile. It's most likely a problem that rustlib resides in /usr/lib64, and the folder isn't scanned by cargo-bloat.

**Comment by RazrFalcon** [comment]
The problem is that I don't know where `rustlib` is. Currently, `cargo-bloat` uses [the same algorithm](https://github.com/RazrFalcon/cargo-bloat/blob/88505bcbd56fd6bf6cfa6256b309b45d8a893daf/src/main.rs#L407) as `rustc`.

Maybe your distro has a patched rust?

**Comment by stefson** [comment]
here's the file list: [rust-files.gz](https://github.com/RazrFalcon/cargo-bloat/files/3998978/rust-files.gz)

**Comment by RazrFalcon** [comment]
Looks like a bug of your distro. Library should be in 

```
/usr/lib64/rustlib/x86_64-unknown-linux-gnu/lib
```
 and not in 

```
/usr/lib64/rust-1.39.0/rustlib/x86_64-unknown-linux-gnu/lib
```

**Comment by stefson** [comment]
I initially thought it was the fact that it resides in /usr/lib64, since all debian based distros don't distinguish lib and lib64, but it makes sense to me. Will test now.

**Comment by stefson** [comment]
this got triggered by a bug in gentoo, as you mentioned. This is now fixed, gentoo bug for reference: https://bugs.gentoo.org/703744

thanks for pointing me towards it! :)

**Comment by RazrFalcon** [comment]
Glad to hear, since I'm using Gentoo too. =) Only I'm installing Rust via rustup.

**Comment by o01eg** [comment]
> Currently, `cargo-bloat` uses [the same algorithm](https://github.com/RazrFalcon/cargo-bloat/blob/88505bcbd56fd6bf6cfa6256b309b45d8a893daf/src/main.rs#L407) as `rustc`.

`rustc` found out alternative libdir because it compiled with alternative `CFG_LIBDIR_RELATIVE` environment:

https://github.com/rust-lang/rust/blob/a916ac22b9f7f1f0f7aba0a41a789b3ecd765018/src/librustc_session/filesearch.rs#L159

**Comment by RazrFalcon** [comment]
Can I access it via CLI?

**Comment by o01eg** [comment]
No yet, I'm think it better to expose it with --print=libdir or so.

**Comment by o01eg** [comment]
@RazrFalcon I've opened PR: https://github.com/rust-lang/rust/pull/69608
