### ISSUE TITLE
Offer prebuilt release binaries

### ISSUE THREAD

**Issue by orf** [RazrFalcon/cargo-bloat#52]
Thanks for this awesome tool! I'm building a github action to run `cargo bloat` on projects. Would you be willing to add support for distributing pre-built binaries via github releases, for environments where a `cargo install` would be too slow or expensive?

This can be entirely automated with Github actions themselves.

**Comment by RazrFalcon** [comment]
>for environments where a cargo install would be too slow or expensive?

`cargo-bloat` takes few seconds to build. That's one of the core features.

Supporting prebuild binaries is too troublesome. I prefer not to.

Also, I'm not sure why do you need `cargo-bloat` on CI.

**Comment by orf** [comment]
> cargo-bloat takes few seconds to build. That's one of the core features.

It depends on the system, it can take upwards of a minute.

> Supporting prebuild binaries is too troublesome. I prefer not to.

Honestly I've found them to be not troublesome at all, but that's that's totally fine 👍. Even without the prebuilt binaries it may be worth looking at Github actions instead of Travis for the CI.

> Also, I'm not sure why do you need cargo-bloat on CI.

I'm working on a experimental personal project to use `cargo bloat` to track binary sizes in projects over time, and give feedback on changes within a merge request.

**Comment by RazrFalcon** [comment]
I'm not familiar with GitHub actions and I don't have enough time to learn them right now, so maybe later. For now, you can host your own builds if build time is critical. If more people find it useful then I will reconsider this.

**Comment by orf** [comment]
I just wanted to let you know that I finally got around to releasing the github-action tool based on cargo-bloat: https://github.com/orf/cargo-bloat-action

Thanks for your work on this project 🙏. I ended up installing a`cargo-bloat` with `--development` to speed up installs, but even then it can take upwards of a minute. I guess that's not too bad, but I'm more than happy to help if you reconsider github-actions in the future.

**Comment by RazrFalcon** [comment]
Hi! Yes, I saw your project. Nice work. I don't use github actions, though.

As for this issue in particular, can we simply publish a prebuilt 64bit version with musl just for linux? Will it be enough?

**Comment by orf** [comment]
Sure, that would be enough, if you're willing to do that. Honestly though, it's fine for now. Maybe with the next release?

**Comment by RazrFalcon** [comment]
I can attach a binary to the latest release on github. I don't need to update anything.

**Comment by orf** [comment]
Ok, that would be fantastic. I can update the workflow to use that pretty easily.

**Comment by RazrFalcon** [comment]
Done.

PS: it takes just 3sec on my machine... The CI hardware must be really slow.
