### ISSUE TITLE
Web assembly (wasm) support?

### ISSUE THREAD

**Issue by jplatte** [RazrFalcon/cargo-bloat#56]
Not sure how realistic that is, but for wasm builds size matters a lot, so having cargo bloat support it would be fantastic.

**Comment by RazrFalcon** [comment]
There is [twiggy](https://github.com/rustwasm/twiggy) for that.

**Comment by JAicewizard** [comment]
@RazrFalcon can you put it in the readme? it is very unfindable and since this is the default for every platform (besides windows) it would be nice to the twiggy author and all the people looking for it.

**Comment by RazrFalcon** [comment]
@JAicewizard done.
