### ISSUE TITLE
Only text section returned when passing `--release`

### ISSUE THREAD

**Issue by SirWindfield** [RazrFalcon/cargo-bloat#58]
I just tried the tool out but I do come across odd behavior. According to all examples inside the readme file, this should work: `cargo bloat --release -n 10`. But I get this output instead:

```
me@tokyo:/p/projects/rust/git-cm$ cargo bloat --release -n 10
    Finished release [optimized] target(s) in 0.12s
    Analyzing target/release/git-cm

File  .text Size Crate Name
0.0%   NaN%   0B       And 0 smaller methods. Use -n N to show more.
0.0% 100.0%   0B       .text section size, the file size is 1.7MiB
```

**Comment by RazrFalcon** [comment]
What is your target? Can you send the binary itself?

**Comment by SirWindfield** [comment]
I am compiling on Ubuntu 18.04 LTS on WSL. The target is  `1.41.0-x86_64-unknown-linux-gnu`.
I deleted the target folder and re-compiled the program and now it works. Looks like I ran `strip` on it before running `cargo bloat --release`. And cargo doesn't check the signature, just if the file is present on the system.

If you happen to know why calling `strip` removes the ability to properly use `cargo-bloat`, could you explain it to me? :)

**Comment by RazrFalcon** [comment]
Yes, this is the expected result. `strip` removes information used by `cargo-bloat`. And no, `cargo-bloat` doesn't check that you have modified the binary. And I'm not sure if this even possible. Unless `cargo` stores checksum of the original binary somewhere.

**Comment by SirWindfield** [comment]
Ah OK, thanks for letting me know! I was just surprised that cargo doesn't store the checksum and instead just checks if the file exists. Maybe this might be a QoL improvement for cargo 🤔
