### ISSUE TITLE
What are the rest 74% not covered by output?

### ISSUE THREAD

**Issue by vimmerru** [RazrFalcon/cargo-bloat#60]
Hi,

If just aggregate output from README.md it will be 26,2% in total only. What are the rest 74% not covered by output?

See attached screenshot 

![Screen Shot 2020-08-31 at 16 21 38](https://user-images.githubusercontent.com/16944801/91724683-55837b00-eba6-11ea-8bf2-44cdc2b18f9f.png)

**Comment by RazrFalcon** [comment]
`cargo-bloat` parser only the `.text` section. There are many more sections, which are more or less optional/irrelevant. Here is [a list of sections](https://en.wikipedia.org/wiki/Executable_and_Linkable_Format#Section_header) for ELF.

As for 26.2%, the last row is *total*. So 13.3% is a `.text` section size in the file. As mentioned in the *Name* column.

**Comment by vimmerru** [comment]
@RazrFalcon Yea... understand. Thanks for the explanation, but seems size analysis based on "text" section only doesn't help a lot in optimization as there is very limited correlation between total size and text section size.

**Comment by RazrFalcon** [comment]
All other sections are optional. Only the `.text` section contains your code. You can run `strip` on Linux and similar commands on other OS'es and most of the section will be removed. 

On the other hand, `cargo-bloat` indeed doesn't support static variables yet. But it should not affect the results in most cases.

**Comment by vimmerru** [comment]
In my specific case i got the following after `strip`. Text is 55%

![image](https://user-images.githubusercontent.com/16944801/91738601-5eca1300-ebb9-11ea-89e1-0f88b6bdd63c.png)

Maybe other sections size correlates to text section size too.

**Comment by RazrFalcon** [comment]
350KiB for `.rodata` is a lot... And as mentioned, `cargo-bloat` doesn't supports constant/static data yet. This is basically #10

**Comment by vimmerru** [comment]
> This is basically #10 

I agree. Feel free to close the issue. I got the answers. Maybe a bit of explanation in readme will help. Thanks!
