### ISSUE TITLE
Add `--tests` flag?

### ISSUE THREAD

**Issue by smoelius** [RazrFalcon/cargo-bloat#67]
I added a `--tests`  flag to my local copy. It wasn't a very big change and it seems to work. Would you like a PR?

This is a really nice tool, BTW. `cargo bloat --time` is super useful.

**Comment by RazrFalcon** [comment]
We already have `--test`. Not sure why we need tests. What binary it will check?

**Comment by smoelius** [comment]
The one that contains the package's unit tests.

If I understand the code correctly, `cargo bloat` simply forwards `--test` on to `cargo build`. According to the Cargo Book, `--test` can only be used to build integration tests: https://doc.rust-lang.org/cargo/commands/cargo-build.html#target-selection

Please let me know if I've misundertood something.

**Comment by RazrFalcon** [comment]
Yes. `--test` is uses to analyse integration tests. And `--tests` builds all tests, including unit tests. So the question is what binary should we analyse in this case.

**Comment by smoelius** [comment]
I am using the `--time` feature. For this case, I don't see why there must be just one binary. Indeed, by forwarding `--tests` to `cargo build`, `cargo bloat` produces sensible results.

Have said that, if the tool's "philosophy" is to operate on a single binary, I can respect that.

Is there another combination of flags that one can pass to `cargo bloat` to cause it to analyze a crate's unit test binary?

**Comment by RazrFalcon** [comment]
>Have said that, if the tool's "philosophy" is to operate on a single binary, I can respect that.

Yes, it's single binary only.

I just don't understand what are you trying to achieve. There are no point in analysing unit tests.

**Comment by smoelius** [comment]
> I just don't understand what are you trying to achieve.

To determine why building unit tests is taking so long. And with this tiny modification, `cargo bloat` solves my use case perfectly. Here is some sample output:
```
$ cargo bloat --time --tests
  Time Crate
37.97s cargo
15.74s syn
13.22s clap
...
```
> There is no point in analysing unit tests.

I can't see why there is no point in analyzing unit tests, yet there is a point in analyzing integration tests.

Anyway, my original question was whether you would like a PR. And I am sensing that the answer is "no." So I am just going to close this issue.

Thanks again for a really useful tool.
