### ISSUE TITLE
Support analyzing dynamic libraries

### ISSUE THREAD

**Issue by bjorn3** [RazrFalcon/cargo-bloat#68]

**Comment by RazrFalcon** [comment]
What dynamic libraries? `cdylib` is already supported. `rlib` is not and not planed.

**Comment by bjorn3** [comment]
I have a project with a `dylib` (not `cdylib`) and a couple binaries. `cargo bloat` picks one of the binaries and doesn't allow me to pass `--lib` to pick the `dylib` instead.

**Comment by RazrFalcon** [comment]
`dylib`  is not supported and not planned.

**Comment by bjorn3** [comment]
Why not? The exact same analysis for `cdylib` should work just fine for `dylib`. A `dylib` is just another dynamic library. It only has an extra `.rustc` section compared to `cdylib` and more exported symbols.

**Comment by RazrFalcon** [comment]
I have no idea how `dylib` is structured. I thought it uses a custom format.

**Comment by bjorn3** [comment]
It uses the same file format as a native dynamic library just like `cdylib`. Otherwise the dynamic linker wouldn't be able to load it.
