### ISSUE TITLE
Does not work on cdylib crates

### ISSUE THREAD

**Issue by sdroege** [RazrFalcon/cargo-bloat#7]
It only prints "No binaries are built."

This seems different from https://github.com/RazrFalcon/cargo-bloat/issues/5

**Comment by RazrFalcon** [comment]
It can't be done. See https://github.com/RazrFalcon/cargo-bloat/issues/5#issuecomment-356292985 for details.

**Comment by sdroege** [comment]
cdylibs don't contain generic code, can do LTO, etc. and there is no Rust metadata left either. Only a couple of C symbols are exported. It's basically like an executable.

**Comment by RazrFalcon** [comment]
Well, I was wrong about `cdylib`. `goblin` supports `.so` and I don't tested `dylib` yet. So at least Linux support for `cdylib` can be implemented.

**Comment by CryZe** [comment]
It seems like static libs are just multiple object files archived together and nm works just fine with that too. I'm not sure if linking would do additional pruning afterwards though, so that may have some influence, but I think at least some support for static libraries might possibly make sense too. What do you think @sdroege?

**Comment by sdroege** [comment]
I don't know how static libs work in details, so no opinion on that.

**Comment by RazrFalcon** [comment]
Done.

**Comment by CryZe** [comment]
I just tried it and it doesn't seem to work:
```
   Compiling livesplit-core-capi v0.8.1 (file:///mnt/home/CryZe/workspace/livesplit-core/capi)
    Finished release [optimized] target(s) in 162.28 secs
Only 'bin' and 'cdylib' targets are supported.
```

```
$ ls ../target/release/
build/                       liblivesplit_core_capi.d
.cargo-lock                  liblivesplit_core_capi.rlib
deps/                        liblivesplit_core_capi.so
examples/                    liblivesplit_core.rlib
.fingerprint/                liblivesplit_hotkey.rlib
incremental/                 native/
liblivesplit_core_capi.a     
```

**Comment by sdroege** [comment]
Also does not work here, but differently:

```
    Finished release [optimized + debuginfo] target(s) in 0.0 secs
thread 'main' panicked at 'called `Result::unwrap()` on an `Err` value: StripPrefixError(())', /checkout/src/libcore/result.rs:906:4
stack backtrace:
   0: std::sys::imp::backtrace::tracing::imp::unwind_backtrace
             at /checkout/src/libstd/sys/unix/backtrace/tracing/gcc_s.rs:49
   1: std::sys_common::backtrace::_print
             at /checkout/src/libstd/sys_common/backtrace.rs:68
   2: std::panicking::default_hook::{{closure}}
             at /checkout/src/libstd/sys_common/backtrace.rs:57
             at /checkout/src/libstd/panicking.rs:381
   3: std::panicking::default_hook
             at /checkout/src/libstd/panicking.rs:397
   4: std::panicking::rust_panic_with_hook
             at /checkout/src/libstd/panicking.rs:577
   5: std::panicking::begin_panic
             at /checkout/src/libstd/panicking.rs:538
   6: std::panicking::begin_panic_fmt
             at /checkout/src/libstd/panicking.rs:522
   7: rust_begin_unwind
             at /checkout/src/libstd/panicking.rs:498
   8: core::panicking::panic_fmt
             at /checkout/src/libcore/panicking.rs:71
   9: core::result::unwrap_failed
             at /checkout/src/libcore/macros.rs:23
  10: <core::result::Result<T, E>>::unwrap
             at /checkout/src/libcore/result.rs:772
  11: cargo_bloat::process_bin
             at src/main.rs:166
  12: cargo_bloat::real_main
             at src/main.rs:143
  13: cargo::call_main_without_stdin
             at /home/slomo/.cargo/registry/src/github.com-1ecc6299db9ec823/cargo-0.24.0/src/cargo/lib.rs:128
  14: cargo_bloat::main
             at src/main.rs:99
  15: __rust_maybe_catch_panic
             at /checkout/src/libpanic_unwind/lib.rs:101
  16: std::rt::lang_start
             at /checkout/src/libstd/panicking.rs:459
             at /checkout/src/libstd/panic.rs:365
             at /checkout/src/libstd/rt.rs:58
  17: main
  18: __libc_start_main
  19: _start

```

**Comment by RazrFalcon** [comment]
@sdroege it's a different error. What is your `pwd`? Because it crashed there.

**Comment by sdroege** [comment]
path is "/home/slomo/Projects/rust/gst-plugin-rs/target/release/deps/libgstrsaudiofx.so", pwd is "/home/slomo/Projects/rust/gst-plugin-rs/gst-plugin-audiofx". Maybe it's confused because it's a sub-crate inside a cargo workspace?

**Comment by CryZe** [comment]
If mine would get that far, it would probably also crash there if that's the case.

**Comment by sdroege** [comment]
FWIW, commenting out the println makes it work correctly.

**Comment by RazrFalcon** [comment]
@sdroege Yes. It works only when `target` folder is in the same folder.

@CryZe `crate-type` with multiple values was not supported. Fixed.

**Comment by sdroege** [comment]
> @sdroege Yes. It works only when target folder is in the same folder.

Should I open a new issue about that then, for more complete workspace support? Also it seems to work fine already except for the println!

**Comment by RazrFalcon** [comment]
@CryZe looks like I can't get a library path if `crate-type` has more that one value. Will open a cargo bug.

**Comment by RazrFalcon** [comment]
@sdroege yes, the bug is in println line.  I will remove it for now and try to test with more complex workspaces.

**Comment by sdroege** [comment]
For the println!, this should be able to just use Path::file_name instead of the component stripping it does right now, or not?

**Comment by RazrFalcon** [comment]
@sdroege yes, but I removed it completely for now.

**Comment by RazrFalcon** [comment]
@CryZe fixed.

**Comment by sdroege** [comment]
Great, thanks!
