### ISSUE TITLE
Build script analyzed instead of a static lib

### ISSUE THREAD

**Issue by jpochyla** [RazrFalcon/cargo-bloat#70]
I have a `crate-type = ["staticlib"]`, with a custom and non-trivial `build.rs` file. `cargo bloat` analyzes the build script instead of the library:

```
$ cargo bloat
Finished dev [unoptimized + debuginfo] target(s) in 0.04s
Analyzing ../../build/unix/rust/debug/build/xxx-b6a1ed629c635974/build-script-build
```

I've tried to fiddle with the parameters, but couldn't find any working combination.

**Comment by RazrFalcon** [comment]
Yes, target binary detection is not trivial. `cargo` returns just a list of all artifacts.

Can you post `cargo build --message-format=json` output? You can remove sensitive info from it.

**Comment by jpochyla** [comment]
I should mention that I'm using a custom `target-dir` set in `.cargo/config.toml`.

> Also, `staticlib` isn't allowed anyway.

Oh, I misunderstood https://github.com/RazrFalcon/cargo-bloat/issues/5#issuecomment-356356716 then?

**Comment by RazrFalcon** [comment]
>I should mention that I'm using a custom

It doesn't matter. I'm simply running `cargo build` and parsing it's output.

**Comment by RazrFalcon** [comment]
>Oh, I misunderstood #5 (comment) then?

Probably. `staticlib` contains unoptimized code. There is no point it analyzing it. You have to analize the final product, aka exe or dll/so/dylib (which is the same as exe, but without main).
