### ISSUE TITLE
Cargo bloat doesn't forward compiler errors on build failure

### ISSUE THREAD

**Issue by appetrosyan** [RazrFalcon/cargo-bloat#76]
I'm using cargo bloat in a GitHub CI action for `iroha` and I'm getting an extremely unhelpful message
```
error: could not compile `iroha_permissions_validators` due to 3 previous errors
Error: failed to execute 'cargo build'. Probably a build error.
```

I've narrowed the issue down to it being related to the `--all-features` flag. I wish I could say more... I would if the error message at least mentioned what those 3 previous errors are.

**Comment by appetrosyan** [comment]
Can we forward the messages to the user? I figured out what went wrong, and it turned out to be a subtle bug in the way our features depended on each other. It would have been very helpful if the original error message was printed in the CI.

**Comment by RazrFalcon** [comment]
As far as I know - no. You just have to run `cargo build` beforehand.

**Comment by nico-abram** [comment]
Would it be a decent workaround to have cargo-bloat first invoke cargo normally, and then forward the exact stdout in the case of a build failure? Before re-invoking cargo the way it does now, with --message-format=json . I think that should not trigger a rebuild

**Comment by RazrFalcon** [comment]
Yes, this is an interesting solution. Patches are welcome.
