### ISSUE TITLE
How to examine other sections in the `.so` file?

### ISSUE THREAD

**Issue by fzyzcjy** [RazrFalcon/cargo-bloat#84]
Hi thanks so much for this library! I can happily examine the `.text` section now. However, I also want to know what happens to the `.rodata` section since it is also quite big. I wonder whether this is available?

**Comment by RazrFalcon** [comment]
`.rodata` is planed #66 but it's a very hard task.

All other sections are mostly useless and small.

**Comment by fzyzcjy** [comment]
@RazrFalcon Ok... Thank you all the same! 

Can we mimic what google's bloaty does?

**Comment by RazrFalcon** [comment]
Afaik, `bloaty` uses disassembly and I'm not sure what targets are supported (except Linux x86). Basically, it's close to impossible to decipher. At least I have no idea how to do this.

**Comment by fzyzcjy** [comment]
I see... Thank you all the same!
