### ISSUE TITLE
Error: parsing failed cause 'section .symtab is missing'.

### ISSUE THREAD

**Issue by fosskers** [RazrFalcon/cargo-bloat#86]
I've been getting this error recently, and even rebuilding `cargo-bloat` doesn't fix it. I've also tried clearing `target/release/`, but the result is the same. Have you seen this before?

Thank you kindly.

**Comment by fosskers** [comment]
Sure thing:

- OS: Arch Linux
- Rust: Stable `1.61.0`
- Target: native with `--release`

**Comment by RazrFalcon** [comment]
I don't have linux right now. Can you send a binary? Doesn't it reproducible on a new, empty project?

**Comment by RazrFalcon** [comment]
No, C shouldn't affect anything.

**Comment by fosskers** [comment]
Let me try it on other projects.

**Comment by fosskers** [comment]
Here's another project of mine that I still see the error on: https://github.com/fosskers/cargo-aur

**Comment by RazrFalcon** [comment]
Try removing `strip = true`.

**Comment by fosskers** [comment]
That fixed it, thank you!

 I guess `strip` breaks `cargo bloat` in a fundamental way?

**Comment by RazrFalcon** [comment]
`strip` removes function names, which is what `cargo bloat` uses to show you the output.

I will see if there is a way to detect the `strip` flag and show a more meaningful error.

**Comment by maxrdz** [comment]
Had the same issue here, due to stripping symbols.

Would totally consider contributing towards this, but I've been reading into multiple rust library sources recently already and I can't get side tracked right now lol. Great project!
