### ISSUE TITLE
Detect `strip = true` in Cargo.toml

### ISSUE THREAD

**Issue by RazrFalcon** [RazrFalcon/cargo-bloat#87]
We should detect it early, otherwise a caller will get a confusing error, since `strip` will remove all function names, which we need.

**Comment by SirVer** [comment]
I actually just ran into this very problem, wanting to report a bug I found this one.

**Comment by qkzk** [comment]
May be it could be specified in the readme, avoiding some digging in the issues.

**Comment by RazrFalcon** [comment]
It's still broken, since I have no idea how to detect if `strip` was set, but at least it should print a warning now.
