### ISSUE TITLE
Total time using cargo bloat --time?

### ISSUE THREAD

**Issue by archsolar** [RazrFalcon/cargo-bloat#94]
Wouldn't it be cool if it also returned total time passed? Would that not be _legendary_?
```
% cargo bloat --time -j 1
 Time Crate
1.42s pdb
1.37s regex_syntax
1.11s cargo_bloat
0.96s regex
------------------ //added:
4.86s TOTAL
```

**Comment by RazrFalcon** [comment]
As the output is sayin, you should prefer `cargo --timings`. `cargo bloat --time` is deprecated.

**Comment by archsolar** [comment]
alright
