### ISSUE TITLE
missing releases on github

### ISSUE THREAD

**Issue by 0-wiz-0** [RazrFalcon/cargo-bloat#96]
I've packaged cargo-bloat for pkgsrc using the github tarball. It has been pointed out to me that on crates.io there is a newer version available. Can you please provide the (tags for the) releases on github as well?

**Comment by RazrFalcon** [comment]
All git tags are present. Are you talking about the prebuilt cargo-bloat specifically?

**Comment by 0-wiz-0** [comment]
Sorry, that was github's interface confusing me.
The start page of the project shows the 0.9.3 release as latest.
If I click on it and through to the tags, I see that all are avaiable. Thanks!
