### ISSUE TITLE
Info on the Size Calculation

### ISSUE THREAD

**Issue by thekief** [RazrFalcon/cargo-bloat#97]
First of all, thank you for the awesome tool. While checking an executable of ours a question has arisen that could not be answered by the documentation:

Do the estimated size include transtitive dependencies or only the function size in the respective crate? 

I recently looked into **yaml-rust** and **serde**; to our suprise **yaml-rust** seems to be much bigger compared to **serde**, although latter seems to depend on much more projects, potentially adding additional size.

**Comment by RazrFalcon** [comment]
`cargo-bloat` simply pretty-prints the information already stored in your executable. Which includes all compiled functions from all the dependencies you use.

**Comment by thekief** [comment]
When using `cargo-tree` one can see the depenedencies of depenedencies. That is what I meant by sub-dependencies. 
Your comment answerered my question/guess related to them

**Comment by RazrFalcon** [comment]
Got it. Everything you see in `cargo-tree` will be in `cargo-bloat` as well. Except for procedural macros implementations (not the generated code) and build scripts, since those are compiled into separate binaries.
