### ISSUE TITLE
[Q&A] Is there a tool or plugin that uses `cargo bloat` information to point at duplication due to monomorphization?

### ISSUE THREAD

**Issue by Byron** [RazrFalcon/cargo-bloat#99]
This question is related [this PR](https://github.com/Byron/gitoxide/pull/992) over at `gitoxide` where I believe that it would be great if there was a tool that can point at duplication of functions that are internal to `gix`. These should all be avoidable after all.

The information that `cargo bloat` provides, especially with `json` output, should suffice to have a tool crunch the data to provide a list of functions that would benefit most from deduplication.

Does such a tool already exist, or is it planned to have in `cargo bloat`? 
Thanks for sharing your thoughts.

*Please feel free to close this issue as it's not an issue, just a way to ask this question before we try to build such a tool.*

CC: @NobodyXu

**Comment by RazrFalcon** [comment]
People were suggesting (#19) to group such methods, but we can try filtering them as well.
It's definitely interesting and useful. Not sure how hard it would be to strip types from generic functions. I worry there would be false-positives.
